config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  get 'pages/home'
  get 'pages/shopping'
  get 'pages/users'
  get 'pages/library'
  get 'pages/article_list'
  resources :topics
  resources :articles
  resources :cultures
  resources :clans
 
 root to: 'pages#home'











end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new

  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:article_link, :article_title, :article_note, :culture_id, :topics_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <% @cultures = Culture.all %>
    <% @topics = Topic.all %>


  <div class="field">
    <%= form.label :culture_id %>
    <%= form.collection_select :culture_id, @cultures, :id, :culture, include_blank: true %>
  </div>

  <div class="field">
    <%= form.label :topics_id %>
    <%= form.collection_select :topics_id, @topics, :id, :topic, include_blank: true  %>
    <%= link_to 'New Topic', new_topic_path%>
  </div>

  <div class="field">
    <%= form.label :article_link %>
    <%= form.text_field :article_link, :size=>"80"  %>
  </div>

  <div class="field">
    <%= form.label :article_title %>
    <%= form.text_field :article_title, :size=>"80" %>
  </div>

  <div class="field">
    <%= form.label :article_note %>
    <%= form.text_field :article_note, :size=>"80" %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Entry"%>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class = "margin5">
<nav><%=render partial: 'shared/navlinks'%></nav>
<h1>Editing Article</h1>
</div>
<body class = "art_page">
<div class = "margin5">
<div class = "col-md-2"></div>
<div class = "col-md-8">

<%= render 'form', article: @article %>
</div>
</div>

app/views/articles/index.html.erb
<body class = "art_page">
<p id="notice"><%= notice %></p>
<nav><%=render partial: 'shared/navlinks'%></nav>
<h1>Articles</h1>

<table width="50%">
  <thead>
    <tr>
      <th>Article title</th>
      <th>Article note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.article_title %></td>
        <td><%= article.article_note %></td>
        <td><%= link_to 'Show', article, class: "btn art_butt" %></td>
        <td><%= link_to 'Edit', edit_article_path(article), class: "btn art_butt" %></td>
        <td><%= link_to 'Delete', article, method: :delete, class: "btn art_butt", data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %><hr>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path, class: "btn new_butt" %>


</body>

app/views/articles/new.html.erb
<div class = "margin5">
<nav><%=render partial: 'shared/navlinks'%></nav>
<h1>New Article</h1>
</div>
<body class = "art_page">
<div class = "margin5">
<div class = "col-md-2"></div>
<div class = "col-md-8">

<%= render 'form', article: @article %>

</div>
</div>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Article culture:</strong>
  <%= @article.culture_id %>
</p>

<p>
  <strong>Article topic:</strong>
  <%= @article.topics_id %>
</p>

<p>
  <strong>Article title:</strong>
  <%= @article.article_title %>
</p>

<p>
  <strong>Article note:</strong>
  <%= @article.article_note %>
</p>

<p>
  <strong>Article link:</strong>
  <%= @article.article_link %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>