config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  devise_for :users
  get 'pages/home'
  get 'pages/shopping'
  get 'pages/users'
  get 'pages/library'
  get 'pages/article_list'
  resources :topics
  resources :articles
  resources :cultures
  resources :clans
 
 root to: 'pages#home'











end

app/models/culture.rb
class Culture < ApplicationRecord
end

app/controllers/cultures_controller.rb
class CulturesController < ApplicationController
  before_action :set_culture, only: [:show, :edit, :update, :destroy]

  # GET /cultures
  # GET /cultures.json
  def index
    @cultures = Culture.all
  end

  # GET /cultures/1
  # GET /cultures/1.json
  def show
  end

  # GET /cultures/new
  def new
    @culture = Culture.new
  end

  # GET /cultures/1/edit
  def edit
  end

  # POST /cultures
  # POST /cultures.json
  def create
    @culture = Culture.new(culture_params)

    respond_to do |format|
      if @culture.save
        format.html { redirect_to @culture, notice: 'Culture was successfully created.' }
        format.json { render :show, status: :created, location: @culture }
      else
        format.html { render :new }
        format.json { render json: @culture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cultures/1
  # PATCH/PUT /cultures/1.json
  def update
    respond_to do |format|
      if @culture.update(culture_params)
        format.html { redirect_to @culture, notice: 'Culture was successfully updated.' }
        format.json { render :show, status: :ok, location: @culture }
      else
        format.html { render :edit }
        format.json { render json: @culture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cultures/1
  # DELETE /cultures/1.json
  def destroy
    @culture.destroy
    respond_to do |format|
      format.html { redirect_to cultures_url, notice: 'Culture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_culture
      @culture = Culture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def culture_params
      params.require(:culture).permit(:culture)
    end
end

app/helpers/cultures_helper.rb
module CulturesHelper
end

app/views/cultures/_form.html.erb
<%= form_with(model: culture, local: true) do |form| %>
  <% if culture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(culture.errors.count, "error") %> prohibited this culture from being saved:</h2>

      <ul>
      <% culture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :culture %>
    <%= form.text_field :culture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cultures/edit.html.erb
<h1>Editing Culture</h1>

<%= render 'form', culture: @culture %>

<%= link_to 'Show', @culture %> |
<%= link_to 'Back', cultures_path %>

app/views/cultures/index.html.erb
<p id="notice"><%= notice %></p>
<nav><%=render partial: 'shared/navlinks'%></nav>
<h1>Cultures</h1>

<table>
  <thead>
    <tr>
      <th>Culture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cultures.each do |culture| %>
      <tr>
        <td><%= culture.culture %></td>
        <td><%= link_to 'Show', culture %></td>
        <td><%= link_to 'Edit', edit_culture_path(culture) %></td>
        <td><%= link_to 'Destroy', culture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Culture', new_culture_path %>

app/views/cultures/new.html.erb
<h1>New Culture</h1>

<%= render 'form', culture: @culture %>

<%= link_to 'Back', cultures_path %>

app/views/cultures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Culture:</strong>
  <%= @culture.culture %>
</p>

<%= link_to 'Edit', edit_culture_path(@culture) %> |
<%= link_to 'Back', cultures_path %>